### ISSUE TITLE
getValidationMessages bug?

### ISSUE THREAD

**Issue by arielenter** [jcergolj/laravel-form-request-assertions#10]
It seems that validator messages array uses field names as key instead of rules.

There for:

```
        if ($rule) {
            return $messages[$rule] ?? [];
        }
```
Will always return an empty array. For instance the following readme example doesn't work at all:

```
    $this->createFormRequest(CreatePostRequest::class)
        ->validate(['email' => ''])
        ->assertFails(['email' => 'required'])
	    ->assertHasMessage('Email is required', 'required');
```

And it is not that 'Email is required' is not the current error message for the required translation key (The correct is 'The :attribute field is required.'), but the fact that $validationMessages is always empty.

**Comment by arielenter** [comment]
I guess that if you change:

```
->assertHasMessage('Email is required', 'required');
```
To:
```
->assertHasMessage('Email is required', 'email');
```
It might work, but it doesn't seem like it was the desired behavior, since both getValidationMessages and assertHasMessage uses $rule as its attribute name.

**Comment by arielenter** [comment]
I just tested my theory an it is correct. One may change the readme example as follow

```
        $this->createFormRequest(CreatePostRequest::class)
                ->validate(['email' => ''])
                ->assertFails(['email' => 'required'])
                ->assertHasMessage('The email field is required.', 'email');
```

To make it work, so a work around for now is to remember to use the field name instead of the rule. To fix the bug I'll recommend to change the attribute name and the readme example. Thank you.

**Comment by jcergolj** [comment]
Hey @arielenter, thanks for finding the bug. Would it be possible to make a PR with readme update? No worries if not, I'll do it myself on Monday. Cheers.

**Comment by jcergolj** [comment]
Resolved and merged.
