### ISSUE TITLE
methods not found in trait

### ISSUE THREAD

**Issue by longestdrive** [jcergolj/laravel-form-request-assertions#2]
Hi
Looking to use the package in testing requests and set up as described and added the trait to my test.
However with this example code:
```
$this->createFormRequest(CreateLeagueRequest::class)
            ->withParams($attributes)
            ->assertPasses();
```

I'm getting errors as the method `assertPasses`doesn't exist in the trait - this does appear in the `TestValidationClass` but can't see how this is referenced in the trait or how best to get this to work - am I missing a set up step?

**Comment by jcergolj** [comment]
Hey, have you included the TestableFormRequest trait inside the test class?
